name: JaxUXGuy
favicon: null
layout_spectrum: 0.7373325265944004
typography_spectrum: 0.07395308837294579
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3859767613466829
  lightness: 0.8699789186939597
  saturation: 0.9707411811687052
  rhythmicContrast: 0.4584049913100898
purpose: []
