name: JaxUXGuy
favicon: null
layout_spectrum: 1
typography_spectrum: 0.89978
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#053e6a'
    - '#7b85ac'
    - '#a2b0d3'
    - '#3d5417'
    - '#f3e3e3'
  brandStrength: 0.3125
  lightness: 0.75
  saturation: 0.9707411811687052
  rhythmicContrast: 0.5
purpose: []
